# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=45)),
                ('scientific_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='species_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenology.SpeciesType'),
        ),
    ]
